from fastapi import FastAPI
from routes.ingest import router as ingest_router
from routes.query import router as query_router
from routes.delete_namespace import router as delete_namespace_router
from routes.delete_document import router as delete_document_router

# Create the FastAPI app
# title and version appear in the auto-generated docs at localhost:8001/docs
app = FastAPI(
    title="AI Study Buddy — Python Client",
    version="0.1.0",
    description="RAG pipeline service. Handles document ingestion and AI-powered querying."
)

# Mount routers
# Each router lives in its own file — main.py only wires things together
# It never implements logic directly
app.include_router(ingest_router)
app.include_router(query_router)
app.include_router(delete_namespace_router)  # POST /delete-namespace — called on session delete
app.include_router(delete_document_router)   # POST /delete          — called on document delete


@app.get("/health")
def health():
    """
    The first endpoint your teammate's Node backend will call.
    Render also pings a health endpoint to decide if the container is alive.

    Always have one. Always keep it simple.
    If this returns 200, the service is up and reachable.
    """
    return {"status": "ok", "service": "python-client", "port": 8001}


# To run locally:
#   uvicorn main:app --reload --port 8001
#
# Then test:
#   GET  http://localhost:8001/health
#   POST http://localhost:8001/ingest            (with x-service-key header)
#   POST http://localhost:8001/query             (with x-service-key header)
#   POST http://localhost:8001/delete-namespace  (with x-service-key header)
#   POST http://localhost:8001/delete            (with x-service-key header)
#
# Interactive docs (auto-generated by FastAPI):
#   http://localhost:8001/docs
